version: '3'
services:
  mongo:
    stdin_open: true
    restart: always
    image: mongo
  api:
    depends_on:
      - mongo
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - '3000:3000'
  ssr:
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ssr
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '9000:9000'
  nginx:
    depends_on:
      - api
      - ssr
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /Users/synoptic/Desktop/server/certs:/etc/nginx/certs
