version: '3'
services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  ssr:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ssr
    volumes:
      - /app/node_modules
      - ./ssr:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '9000:9000'
  nginx:
    depends_on:
      - api
      - ssr
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
