version: '3'
services:
  mongo:
    stdin_open: true
    restart: always
    image: mongo
    env_file:
      - ./mongo/.env
    ports:
      - 27017:27017
    volumes:
      - ../db:/data/db
  api:
    depends_on:
      - mongo
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
  ssr:
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ssr
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
  nginx:
    depends_on:
      - api
      - ssr
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /Users/synoptic/Desktop/server/certs:/etc/nginx/certs
