version: '3'
services:
  mongo:
    image: "synopticum/urussu-mongo"
  api:
    depends_on:
      - mongo
    image: "synopticum/urussu-api"
  ssr:
    image: "synopticum/urussu-ssr"
  client:
    image: "synopticum/urussu-client"
    ports:
      - '9000:9000'
  nginx:
    depends_on:
      - api
      - ssr
      - client
    restart: always
    image: "synopticum/urussu-nginx"
    ports:
      - '80:80'
