name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_SSH_USERNAME }}
          password: ${{ secrets.HOST_SSH_PASSWORD }}
          script: |
            export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            bash ./deploy/stop.sh
            cp ../../env/u-r-u-s-s-u.com/.client-env ./client/.env
            cp ../../env/u-r-u-s-s-u.com/.mongo-env ./mongo/.env
            cp ../../env/u-r-u-s-s-u.com/.api-env ./api/.env
            cp ../../env/u-r-u-s-s-u.com/.ssr-env ./ssr/.env
            docker-compose up -d --build
          script_stop: true
          command_timeout: 30m
